.build-template:
  stage: test
  script:
    - |
      apk add --update curl && rm -rf /var/cache/apk/*
      curl --request POST \
        --form "token=$CI_JOB_TOKEN" \
        --form "ref=release" \
        --form "variables[PASSBOLT_FLAVOUR]=$PASSBOLT_FLAVOUR" \
        --form "variables[UPSTREAM_COMMIT_SHA]=$CI_COMMIT_SHA" \
        --form "variables[UPSTREAM_PROJECT_ID]=$CI_PROJECT_ID" \
        "https://gitlab.com/api/v4/projects/$DOWNSTREAM_PROJECT_ID/trigger/pipeline"
  only:
    - release
  except:
    variables:
      - $PASSBOLT_FLAVOUR == "ce"

pro-trigger-build:
  extends: .build-template

ce-trigger-build:
  extends: .build-template
  except:
    variables:
      - $PASSBOLT_FLAVOUR == "pro"
