.kitchen-test:
  extends: .rules
  image: registry.gitlab.com/passbolt/passbolt-ci-docker-images/ruby:latest
  stage: package-tests
  script:
    - apt update && apt install rsync -y
    - gem install bundler:2.1.2
    - bundle install
    - cat $GL_REGISTRY_CREDS > ./creds.json
    - bundle exec kitchen verify $KITCHEN_JOB -t tests/integration -l debug

# Debian/Ubuntu package testing
#
.kitchen-test-debian:
  extends: .kitchen-test
  needs:
    - job: composer
      artifacts: true
    - job: build-debian
      artifacts: true
  script:
    - apt update && apt install rsync -y
    - gem install bundler:2.1.2
    - bundle install
    - cat $GL_REGISTRY_CREDS > ./creds.json
    - bundle exec kitchen verify $KITCHEN_JOB -t tests/integration -l debug

.kitchen-test-yum:
  extends: .kitchen-test
  needs:
    - job: composer
      artifacts: true
    - job: build-yum
      artifacts: true

.kitchen-test-yum-7:
  extends: .kitchen-test
  needs:
    - job: composer
      artifacts: true
    - job: build-yum-7
      artifacts: true

.kitchen-test-suse:
  extends: .kitchen-test
  needs:
    - job: composer
      artifacts: true
    - job: build-suse
      artifacts: true

debian-buster-runtime:
  extends: .kitchen-test-debian
  needs: ["debian-buster-break"]
  variables:
    KITCHEN_JOB: runtime-benchmarks-debian-buster

debian-bullseye-runtime:
  extends: .kitchen-test-debian
  needs: ["debian-bullseye-break"]
  variables:
    KITCHEN_JOB: runtime-benchmarks-debian-bullseye

ubuntu-1804-runtime:
  extends: .kitchen-test-debian
  needs: ["ubuntu-1804-break"]
  allow_failure: true
  variables:
    KITCHEN_JOB: runtime-benchmarks-ubuntu-1804

ubuntu-2004-runtime:
  extends: .kitchen-test-debian
  needs: ["ubuntu-2004-break"]
  variables:
    KITCHEN_JOB: runtime-benchmarks-ubuntu-2004

centos-7-runtime:
  extends: .kitchen-test-yum-7
  needs: ["centos-7-break"]
  variables:
    KITCHEN_JOB: runtime-benchmarks-centos-7

almalinux-8-runtime:
  extends: .kitchen-test-yum
  needs: ["almalinux-8-break"]
  variables:
    KITCHEN_JOB: runtime-benchmarks-almalinux-8

fedora-34-runtime:
  extends: .kitchen-test-yum
  needs: ["fedora-34-break"]
  variables:
    KITCHEN_JOB: runtime-benchmarks-fedora-34

fedora-35-runtime:
  extends: .kitchen-test-yum
  needs: ["fedora-35-break"]
  variables:
    KITCHEN_JOB: runtime-benchmarks-fedora-35

oraclelinux-8-runtime:
  extends: .kitchen-test-yum
  needs: ["oraclelinux-8-break"]
  variables:
    KITCHEN_JOB: runtime-benchmarks-oraclelinux-8

rockylinux-8-runtime:
  extends: .kitchen-test-yum
  needs: ["rockylinux-8-break"]
  variables:
    KITCHEN_JOB: runtime-benchmarks-rockylinux-8

opensuse-leap-15-runtime:
  extends: .kitchen-test-suse
  needs: ["opensuse-leap-15-break"]
  variables:
    KITCHEN_JOB: runtime-benchmarks-opensuse-leap-15

debian-buster-break:
  extends: .kitchen-test-debian
  needs: ["debian-buster-purge"]
  variables:
    KITCHEN_JOB: break-benchmarks-debian-buster

debian-bullseye-break:
  extends: .kitchen-test-debian
  needs: ["debian-bullseye-purge"]
  variables:
    KITCHEN_JOB: break-benchmarks-debian-bullseye

ubuntu-1804-break:
  extends: .kitchen-test-debian
  needs: ["ubuntu-1804-purge"]
  allow_failure: true
  variables:
    KITCHEN_JOB: break-benchmarks-ubuntu-1804

ubuntu-2004-break:
  extends: .kitchen-test-debian
  needs: ["ubuntu-2004-purge"]
  variables:
    KITCHEN_JOB: break-benchmarks-ubuntu-2004

centos-7-break:
  extends: .kitchen-test-yum-7
  needs: ["centos-7-purge"]
  variables:
    KITCHEN_JOB: break-benchmarks-centos-7

almalinux-8-break:
  extends: .kitchen-test-yum
  needs: ["almalinux-8-purge"]
  variables:
    KITCHEN_JOB: break-benchmarks-almalinux-8

fedora-34-break:
  extends: .kitchen-test-yum
  needs: ["fedora-34-purge"]
  variables:
    KITCHEN_JOB: break-benchmarks-fedora-34

fedora-35-break:
  extends: .kitchen-test-yum
  needs: ["fedora-35-purge"]
  variables:
    KITCHEN_JOB: break-benchmarks-fedora-35

oraclelinux-8-break:
  extends: .kitchen-test-yum
  needs: ["oraclelinux-8-purge"]
  variables:
    KITCHEN_JOB: break-benchmarks-oraclelinux-8

rockylinux-8-break:
  extends: .kitchen-test-yum
  needs: ["rockylinux-8-purge"]
  variables:
    KITCHEN_JOB: break-benchmarks-rockylinux-8

opensuse-leap-15-break:
  extends: .kitchen-test-suse
  needs: ["opensuse-leap-15-purge"]
  variables:
    KITCHEN_JOB: break-benchmarks-opensuse-leap-15

debian-buster-purge:
  extends: .kitchen-test-debian
  needs: ["debian-buster-fs"]
  variables:
    KITCHEN_JOB: purge-benchmarks-debian-buster

debian-bullseye-purge:
  extends: .kitchen-test-debian
  needs: ["debian-bullseye-fs"]
  variables:
    KITCHEN_JOB: purge-benchmarks-debian-bullseye

ubuntu-1804-purge:
  extends: .kitchen-test-debian
  needs: ["ubuntu-1804-fs"]
  allow_failure: true
  variables:
    KITCHEN_JOB: purge-benchmarks-ubuntu-1804

ubuntu-2004-purge:
  extends: .kitchen-test-debian
  needs: ["ubuntu-2004-fs"]
  variables:
    KITCHEN_JOB: purge-benchmarks-ubuntu-2004

centos-7-purge:
  extends: .kitchen-test-yum-7
  needs: ["centos-7-fs"]
  variables:
    KITCHEN_JOB: purge-benchmarks-centos-7

almalinux-8-purge:
  extends: .kitchen-test-yum
  needs: ["almalinux-8-fs"]
  variables:
    KITCHEN_JOB: purge-benchmarks-almalinux-8

fedora-34-purge:
  extends: .kitchen-test-yum
  needs: ["fedora-34-fs"]
  variables:
    KITCHEN_JOB: purge-benchmarks-fedora-34

fedora-35-purge:
  extends: .kitchen-test-yum
  needs: ["fedora-35-fs"]
  variables:
    KITCHEN_JOB: purge-benchmarks-fedora-35

oraclelinux-8-purge:
  extends: .kitchen-test-yum
  needs: ["oraclelinux-8-fs"]
  variables:
    KITCHEN_JOB: purge-benchmarks-oraclelinux-8

rockylinux-8-purge:
  extends: .kitchen-test-yum
  needs: ["rockylinux-8-fs"]
  variables:
    KITCHEN_JOB: purge-benchmarks-rockylinux-8

opensuse-leap-15-purge:
  extends: .kitchen-test-suse
  needs: ["opensuse-leap-15-fs"]
  variables:
    KITCHEN_JOB: purge-benchmarks-opensuse-leap-15

debian-buster-purge:
  extends: .kitchen-test-debian
  needs: ["debian-buster-fs"]
  variables:
    KITCHEN_JOB: purge-benchmarks-debian-buster

debian-bullseye-purge:
  extends: .kitchen-test-debian
  needs: ["debian-bullseye-fs"]
  variables:
    KITCHEN_JOB: purge-benchmarks-debian-bullseye

ubuntu-1804-purge:
  extends: .kitchen-test-debian
  needs: ["ubuntu-1804-fs"]
  allow_failure: true
  variables:
    KITCHEN_JOB: purge-benchmarks-ubuntu-1804

ubuntu-2004-purge:
  extends: .kitchen-test-debian
  needs: ["ubuntu-2004-fs"]
  variables:
    KITCHEN_JOB: purge-benchmarks-ubuntu-2004

centos-7-purge:
  extends: .kitchen-test-yum-7
  needs: ["centos-7-fs"]
  variables:
    KITCHEN_JOB: purge-benchmarks-centos-7

almalinux-8-purge:
  extends: .kitchen-test-yum
  needs: ["almalinux-8-fs"]
  variables:
    KITCHEN_JOB: purge-benchmarks-almalinux-8

fedora-34-purge:
  extends: .kitchen-test-yum
  needs: ["fedora-34-fs"]
  variables:
    KITCHEN_JOB: purge-benchmarks-fedora-34

fedora-35-purge:
  extends: .kitchen-test-yum
  needs: ["fedora-35-fs"]
  variables:
    KITCHEN_JOB: purge-benchmarks-fedora-35

oraclelinux-8-purge:
  extends: .kitchen-test-yum
  needs: ["oraclelinux-8-fs"]
  variables:
    KITCHEN_JOB: purge-benchmarks-oraclelinux-8

rockylinux-8-purge:
  extends: .kitchen-test-yum
  needs: ["rockylinux-8-fs"]
  variables:
    KITCHEN_JOB: purge-benchmarks-rockylinux-8

opensuse-leap-15-purge:
  extends: .kitchen-test-suse
  needs: ["opensuse-leap-15-fs"]
  variables:
    KITCHEN_JOB: purge-benchmarks-opensuse-leap-15

debian-buster-fs:
  extends: .kitchen-test-debian
  dependencies:
    - composer
  variables:
    KITCHEN_JOB: filesystem-benchmarks-debian-buster

debian-bullseye-fs:
  extends: .kitchen-test-debian
  dependencies:
    - composer
  variables:
    KITCHEN_JOB: filesystem-benchmarks-debian-bullseye

ubuntu-1804-fs:
  extends: .kitchen-test-debian
  allow_failure: true
  variables:
    KITCHEN_JOB: filesystem-benchmarks-ubuntu-1804

ubuntu-2004-fs:
  extends: .kitchen-test-debian
  variables:
    KITCHEN_JOB: filesystem-benchmarks-ubuntu-2004

centos-7-fs:
  extends: .kitchen-test-yum-7
  variables:
    KITCHEN_JOB: filesystem-benchmarks-centos-7

almalinux-8-fs:
  extends: .kitchen-test-yum
  variables:
    KITCHEN_JOB: filesystem-benchmarks-almalinux-8

fedora-34-fs:
  extends: .kitchen-test-yum
  variables:
    KITCHEN_JOB: filesystem-benchmarks-fedora-34

fedora-35-fs:
  extends: .kitchen-test-yum
  variables:
    KITCHEN_JOB: filesystem-benchmarks-fedora-35

oraclelinux-8-fs:
  extends: .kitchen-test-yum
  variables:
    KITCHEN_JOB: filesystem-benchmarks-oraclelinux-8

rockylinux-8-fs:
  extends: .kitchen-test-yum
  variables:
    KITCHEN_JOB: filesystem-benchmarks-rockylinux-8

opensuse-leap-15-fs:
  extends: .kitchen-test-suse
  variables:
    KITCHEN_JOB: filesystem-benchmarks-opensuse-leap-15
